import "@/shared/styles/reset.css";

import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";

import Provider from "./provider";

const NotoSans = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={NotoSans.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
